###############################################################
# This is the configuration file that lets the user to select
# order sizes, order types, ticker list, market center IDs for analysis.
# User can also select the project working directory.
# If multiple ranges or types are desired, use comma to separate values
# If no specific value is desired, use "".
# Automatic SEC Rule 605 file downloads are currently supported
# using download_rule605_filings.R for CDRG, JNST, NITE.
# ------------------
# Order Size Mapping
# ------------------
# 100-499 shares - 21
# 500-1999 shares - 22
# 2000-4999 shares - 23
# 5000 or more shares - 24
# ------------------
# Order Type Mapping
# ------------------
# market orders - 11
# marketable limit orders - 12
# inside-the-quote limit orders - 13
# at-the-quote limit orders - 14
# near-the-quote limit orders - 15
# ------------------
# If the project folder is saved in C drive as "DEQ", give project_dir as "C:/DEQ"
################################################################ 
# Provide Input Values below:

default:
  project_dir: "C:/new_DEQ"
  order_type: "11"
  order_size: "21"
  tickers: "AAPL,AMZN,MSFT,GOOG"
  market_center_ids: "CDRG,JNST,NITE"
  
